#!/usr/bin/env python3
"""Generate MODULES.md — a browsable catalog of every published module.

Reads the module list from module-release-config.json (packages), the current
version from .module-versions.json, and a one-line description from each
module's README.md. Emits a table grouped by provider with the registry source
each consumer uses. Re-runnable; run from the repo root or anywhere:

    python3 configs/generate_modules_catalog.py        # writes MODULES.md
    python3 configs/generate_modules_catalog.py --check # fail if out of date

Stdlib only.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "MODULES.md"
NAMESPACE = "c0x12c"
REGISTRY_HOST = "terraform.c0x12c.com"


def registry_source(module: str) -> str:
    # terraform-<provider>-<name> -> terraform.c0x12c.com/c0x12c/<name>/<provider>
    parts = module.split("-")
    provider, name = parts[1], "-".join(parts[2:])
    return "%s/%s/%s/%s" % (REGISTRY_HOST, NAMESPACE, name, provider)


def description(module: str) -> str:
    """First meaningful prose line of the module README (skip headings, badges,
    blockquotes, blanks). Empty string if none."""
    readme = ROOT / module / "README.md"
    if not readme.is_file():
        return ""
    for raw in readme.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ">", "![", "[!", "|", "---", "```")):
            continue
        if len(line) > 110:
            line = line[:107].rstrip() + "..."
        return line
    return ""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if MODULES.md is stale instead of writing it")
    args = ap.parse_args()

    config = json.loads((ROOT / "module-release-config.json").read_text())
    versions = json.loads((ROOT / ".module-versions.json").read_text())
    modules = sorted(config.get("packages", {}).keys())

    rows = []
    for m in modules:
        rows.append((m, registry_source(m), versions.get(m, "?"), description(m)))

    lines = [
        "# Module Catalog",
        "",
        "Auto-generated by `configs/generate_modules_catalog.py` — do not edit by hand.",
        "",
        "%d modules, published to `%s`. Consume any module with:" % (len(rows), REGISTRY_HOST),
        "",
        "```hcl",
        'module "example" {',
        '  source  = "%s"' % rows[0][1] if rows else '  source  = "..."',
        '  version = "~> %s"' % (rows[0][2] if rows else "0.1"),
        "}",
        "```",
        "",
        "| Module | Source | Version | Description |",
        "|---|---|---|---|",
    ]
    for name, source, version, desc in rows:
        lines.append("| `%s` | `%s` | %s | %s |" % (name, source, version, desc))
    content = "\n".join(lines) + "\n"

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != content:
            print("MODULES.md is out of date — run configs/generate_modules_catalog.py",
                  file=sys.stderr)
            return 1
        print("MODULES.md is up to date (%d modules)" % len(rows))
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print("wrote %s (%d modules)" % (OUTPUT.relative_to(ROOT), len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
