version: 1
modules:
  terraform-aws-acm:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-alb:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-amplify:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-cloudfront-logging:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-cloudtrail:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-cloudwatch:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-cloudwatch-alarm:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-ecr:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-ecs-application:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-ecs-cluster:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-efs:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-access-entry:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-cloudwatch-logging-fargate:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-cluster:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-datadog-rbac:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-efs:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-fargate-profile:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-helm:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-managed-node-group:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-rbac:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eks-service:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-elasticache:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-eventbridge-slack-notification:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-github-oidc:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-github-self-hosted-runners:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-guardduty:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-argocd:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-aws-lb-controller:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-datadog:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-jenkins:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-keda:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-keycloak:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-metrics-server:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-nginx-ingress-controller:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-helm-opa:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-iam-sso:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-identity-provider:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-jenkins-oidc:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-kms:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-mwaa:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-oidc:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-oidc-provider:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-opensearch:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-openvpn:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-password-generator:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-password-policy:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-rds:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-saml-idp:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-schedulers:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-secret-manager:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-security-group:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-sendgrid:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-ses:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-ses-monitoring:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-sns:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-sqs:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-ssm-parameter:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-static-website:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-vanta:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-vpc:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-vpc-endpoints:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-aws-vpn:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-cloudflare-record-with-cache-rule:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-aws-integration:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-aws-monitor:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-dashboard:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-ecs-monitor:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-gcp-integration:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-gcp-monitor:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-monitors:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-mono-monitor:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-notification-rules:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-oncall:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-service-monitor:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-team:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-artifact-registry:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-cloud-dns:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-github-oidc:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-gke-autopilot:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-gke-gateway-api:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-gke-ingress:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-google-monitoring:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-google-workspace:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-google-workspace-group:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-iam-member:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-load-balancer-gcs:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-openvpn:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-postgresql:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-project-service:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-recaptcha:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-redis-cluster:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-service-account:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-service-config:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-service-connection-policies:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-storage-bucket:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-vpc:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-wildcard-sslcert:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-gcp-workload-identity:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
  terraform-datadog-logging-monitor:
    applied_features:
      - dependabot-automerge
      - gh-app-secret
